image: node:latest

stages:
  - deploy

deploy_prod:
  stage: deploy
  script:
    - echo "HI '$TI'"
    - npm install -g netlify-cli@latest
    - ls
    - netlify deploy --dir "dist" --auth $AUTH_TOKEN_NETLIFY --site $SITE_ID_NETLIFY --prod
  only:
    - master